#!/usr/bin/env python3
"""Fetch profile-level Google Scholar metrics (citations, h-index, i10-index)
and write them to _data/scholar_stats.yml.

Designed to fail safe: if the profile cannot be fetched or parsed, the existing
data file is left untouched (so the last-known-good values keep showing).
"""
import os
import re
import sys
import time
import random
import datetime
import urllib.request

SCHOLAR_ID = os.environ.get("SCHOLAR_USERID", "CF7dea8AAAAJ")
OUT_PATH = os.environ.get("SCHOLAR_STATS_PATH", "_data/scholar_stats.yml")
PROFILE_URL = (
    "https://scholar.google.com/citations?user={}&hl=en".format(SCHOLAR_ID)
)
UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/124.0 Safari/537.36"
)


def fetch_html(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA, "Accept-Language": "en-US,en"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read().decode("utf-8", "replace")


def parse_metrics(html):
    """Return (citations, h_index, i10_index) from the 'All' column.

    The profile renders six <td class="gsc_rsb_std"> cells in row-major order:
    Citations(All), Citations(Since), h-index(All), h-index(Since),
    i10-index(All), i10-index(Since). We take the 'All' values: indices 0, 2, 4.
    """
    cells = re.findall(r'class="gsc_rsb_std">\s*([\d,]+)\s*<', html)
    nums = [int(c.replace(",", "")) for c in cells]
    if len(nums) < 6:
        raise ValueError("expected >=6 metric cells, got {}: {}".format(len(nums), nums))
    return nums[0], nums[2], nums[4]


def main():
    last_exc = None
    for attempt in range(3):
        try:
            html = fetch_html(PROFILE_URL)
            if "gsc_rsb_std" not in html:
                raise ValueError("metrics block not found (blocked or empty page)")
            citations, h_index, i10_index = parse_metrics(html)
            break
        except Exception as exc:  # noqa: BLE001
            last_exc = exc
            sys.stderr.write("attempt {} failed: {}\n".format(attempt + 1, exc))
            time.sleep(random.uniform(2.0, 5.0))
    else:
        sys.stderr.write("ERROR: could not fetch Scholar metrics: {}\n".format(last_exc))
        return 1

    today = datetime.date.today().isoformat()
    content = (
        "# Auto-generated by scripts/fetch_scholar_stats.py — do not edit by hand.\n"
        "# Profile-level Google Scholar metrics ('All' column).\n"
        "citations: {}\n"
        "h_index: {}\n"
        "i10_index: {}\n"
        "updated_at: '{}'\n"
    ).format(citations, h_index, i10_index, today)

    with open(OUT_PATH, "w") as fh:
        fh.write(content)
    sys.stdout.write(
        "OK citations={} h_index={} i10_index={} -> {}\n".format(
            citations, h_index, i10_index, OUT_PATH
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
