#!/usr/bin/env python3
"""Fetch Google Scholar data in a single pass and write two data files:

  _data/scholar_stats.yml  profile-level metrics (citations, h-index, i10-index)
  _data/citations.yml      per-article citation counts, keyed by google_scholar_id

The keys in citations.yml match the `google_scholar_id` field on each entry in
_bibliography/papers.bib; _layouts/bib.liquid looks counts up by that field.

Designed to fail safe: if the profile cannot be fetched or parsed, both data
files are left untouched, so the last-known-good values keep showing.
"""
import datetime
import os
import random
import re
import sys
import time
import urllib.request

SCHOLAR_ID = os.environ.get("SCHOLAR_USERID", "CF7dea8AAAAJ")
STATS_PATH = os.environ.get("SCHOLAR_STATS_PATH", "_data/scholar_stats.yml")
CITES_PATH = os.environ.get("SCHOLAR_CITES_PATH", "_data/citations.yml")

PAGE_SIZE = 100
PROFILE_URL = (
    "https://scholar.google.com/citations"
    "?user={user}&hl=en&cstart={cstart}&pagesize={pagesize}"
)
UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/124.0 Safari/537.36"
)

ROW_RE = re.compile(r'class="gsc_a_tr"(.*?)(?=class="gsc_a_tr"|</tbody>)', re.S)
ARTID_RE = re.compile(r'citation_for_view=[^:&"]+:([^&"\s]+)')
CITES_RE = re.compile(r'class="gsc_a_ac[^"]*"[^>]*>\s*(\d*)\s*<')


def fetch_html(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA, "Accept-Language": "en-US,en"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read().decode("utf-8", "replace")


def fetch_with_retry(url, attempts=3):
    last_exc = None
    for i in range(attempts):
        try:
            return fetch_html(url)
        except Exception as exc:  # noqa: BLE001
            last_exc = exc
            sys.stderr.write("attempt {} failed: {}\n".format(i + 1, exc))
            time.sleep(random.uniform(2.0, 5.0))
    raise last_exc


def parse_metrics(html):
    """Return (citations, h_index, i10_index) from the 'All' column.

    The profile renders six <td class="gsc_rsb_std"> cells in row-major order:
    Citations(All), Citations(Since), h-index(All), h-index(Since),
    i10-index(All), i10-index(Since). We take the 'All' values: indices 0, 2, 4.
    """
    cells = re.findall(r'class="gsc_rsb_std">\s*([\d,]+)\s*<', html)
    nums = [int(c.replace(",", "")) for c in cells]
    if len(nums) < 6:
        raise ValueError("expected >=6 metric cells, got {}: {}".format(len(nums), nums))
    return nums[0], nums[2], nums[4]


def parse_articles(html):
    """Return {article_id: citation_count} for one page of the profile listing.

    An article with zero citations renders an empty cell; we record it as 0.
    """
    out = {}
    for row in ROW_RE.findall(html):
        m_id = ARTID_RE.search(row)
        if not m_id:
            continue
        m_cites = CITES_RE.search(row)
        out[m_id.group(1)] = int(m_cites.group(1)) if (m_cites and m_cites.group(1)) else 0
    return out


def main():
    articles = {}
    metrics = None
    cstart = 0
    while True:
        url = PROFILE_URL.format(user=SCHOLAR_ID, cstart=cstart, pagesize=PAGE_SIZE)
        try:
            html = fetch_with_retry(url)
        except Exception as exc:  # noqa: BLE001
            sys.stderr.write("ERROR: could not fetch Scholar profile: {}\n".format(exc))
            return 1
        if "gsc_rsb_std" not in html:
            sys.stderr.write("ERROR: metrics block not found (blocked or empty page)\n")
            return 1
        if metrics is None:
            metrics = parse_metrics(html)
        page = parse_articles(html)
        articles.update(page)
        if len(page) < PAGE_SIZE:
            break
        cstart += PAGE_SIZE
        time.sleep(random.uniform(2.0, 4.0))

    if not articles:
        sys.stderr.write("ERROR: no article rows parsed; refusing to overwrite\n")
        return 1

    citations, h_index, i10_index = metrics
    today = datetime.date.today().isoformat()
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    with open(STATS_PATH, "w", encoding="utf-8") as fh:
        fh.write(
            "# Auto-generated by scripts/fetch_scholar_stats.py — do not edit by hand.\n"
            "# Profile-level Google Scholar metrics ('All' column).\n"
            "citations: {}\n"
            "h_index: {}\n"
            "i10_index: {}\n"
            "updated_at: '{}'\n".format(citations, h_index, i10_index, today)
        )

    with open(CITES_PATH, "w", encoding="utf-8") as fh:
        fh.write(
            "# Auto-generated by scripts/fetch_scholar_stats.py — do not edit by hand.\n"
            "# Per-article Google Scholar citation counts, keyed by google_scholar_id.\n"
            "updated_at: '{}'\n"
            "counts:\n".format(now)
        )
        for artid in sorted(articles, key=lambda k: (-articles[k], k)):
            fh.write("  {}: {}\n".format(artid, articles[artid]))

    sys.stdout.write(
        "OK citations={} h_index={} i10_index={} articles={} -> {}, {}\n".format(
            citations, h_index, i10_index, len(articles), STATS_PATH, CITES_PATH
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
